### ISSUE TITLE
Not triggered on shader activation

### ISSUE THREAD

**Issue by Zabooby** [he2a/mpv-scripts#3]
The script doesn't seem to trigger on shader activation (from the uosc menu), it works fine when using a key bind. Here the shaders did not trigger the script, I had to press the key bind to see the shaders. I also tried individual shaders too. 

https://github.com/he2a/mpv-scripts/assets/78969986/049001d7-bd55-46d3-86cd-06506384f2c8

Also what would I need to change for the key bind to only flash current shaders instead of it toggling the list?

**Comment by he2a** [comment]
Yeah, there was a bug that caused the player to crash when files were switched rapidly which is why I removed it before. Should be fixed now. By default it should flash for 2 second when you change shaders.

**Comment by Zabooby** [comment]
Thanks for the fix.
